[bot]

# The bot's API token. Keep this secret!
token = "your-bot-token-here"

# List of owners by user ID
owners = ["98633956773093376", "130012001236811776"]

# Default bot command prefix
prefix = "!"

# Emojis to display for certain icons within the bot
# Set to "0" to disable
[emojis]
python = "490419105699069952"
discordpy = "490419059964510210"

# Path to the RDBMS futaba will use
[database]
url = "sqlite:///futaba.db"
