[bot]

# The bot's API token. Keep this secret!
token = "your-bot-token-here"

# List of owners by user ID
owners = ["98633956773093376", "130012001236811776"]

# Default bot command prefix
prefix = "!"

# The tracebacks of any unexpected errors are uploaded to this file.
# Set to "0" to disable
error-channel-id = "488543452305555456"

[moderation]
# Maximum number of messages that may be specified
# when doing a bulk message cleanup
max-cleanup-messages = "500"

[delay]
# Configuration for the delayed event queue

# How many events are needed to move up one delay bracket
bracket-size = "100"

# How many seconds of wait each new bracket should add
rate = "0.005"

# The maximum pause in sending events, regardless of how full the queue is
max-delay = "0.1"

# Emojis to display for certain icons within the bot
# Set to "0" to disable
[emojis]
anger = "496085813881470986"
python = "490419105699069952"
discordpy = "490419059964510210"

# Path to the RDBMS futaba will use
[database]
url = "sqlite:///futaba.db"
