language: python

stages:
  - black
  - test

jobs:
  include:
    - stage: black
      python: '3.8'
      script:
        - black --check futaba
    - stage: lint
      python:
        - '3.6'
        - '3.7'
        - '3.8'
        - '3.8-dev'
        - 'nightly'
      script:
        # Display all lints and a report
        - pylint --reports=yes futaba

matrix:
  allow_failures:
    - python: 'nightly'
  fast_finish: true

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

notifications:
  email:
    on_success: never
    on_failure: always
