language: python
dist: trusty
sudo: false
cache: pip

python:
  - '3.5'
  - '3.6'
  - '3.7-dev'
  - 'nightly'

matrix:
  allow_failures:
    - python: nightly
  fast_finish: true

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

script:
  # Run a check for black formatting
  - black --check futaba
  # Display all lints and a report
  - pylint --reports=yes futaba || true

  # Only fail on errors
  - pylint --errors-only futaba

notifications:
  email:
    on_success: never
    on_failure: always
